### ISSUE TITLE
fatal error: curl/curl.h: No such file or directory

### ISSUE THREAD

**Issue by MyronSykes** [Dink4n/canime#3]
ubuntu 20.04 3 

![Screenshot from 2021-11-13 03-35-14](https://user-images.githubusercontent.com/94218529/141612447-9fbbc741-40bb-43d7-9417-d2295dc0399c.png)

**Comment by Dink4n** [comment]
You need to install libcurl
```Console
sudo apt install libcurl4
```
I am working on removing the dependency

**Comment by MyronSykes** [comment]
libcurl4 already installed . I install libcurl4-openssl-dev package and after canime installation command work

**Comment by MyronSykes** [comment]
![Screenshot from 2021-11-13 07-47-05](https://user-images.githubusercontent.com/94218529/141646064-02346e63-153c-42a9-ae71-5c5dd2fe7613.png)
